import { Router, type IRouter } from "express";
import healthRouter from "./health.js";
import authRouter from "./auth.js";
import employeesRouter from "./employees.js";
import departmentsRouter from "./departments.js";
import attendanceRouter from "./attendance.js";
import leavesRouter from "./leaves.js";
import payrollRouter from "./payroll.js";
import timesheetsRouter from "./timesheets.js";
import performanceRouter from "./performance.js";
import dashboardRouter from "./dashboard.js";
import brandingRouter from "./branding.js";
import biometricsRouter from "./biometrics.js";
import documentsRouter from "./documents.js";
import holidaysRouter from "./holidays.js";
import announcementsRouter from "./announcements.js";
import policiesRouter from "./policies.js";
import leaveRulesRouter from "./leave-rules.js";
import adminRouter from "./admin.js";
import passwordResetRouter from "./password-reset.js";
import uploadRouter from "./upload.js";
import auditLogsRouter from "./audit-logs.js";
import rolesRouter from "./roles.js";
import exportImportRouter from "./export-import.js";

const router: IRouter = Router();

router.use(healthRouter);
router.use("/auth", authRouter);
router.use("/auth", passwordResetRouter);
router.use("/employees", employeesRouter);
router.use("/departments", departmentsRouter);
router.use("/attendance", attendanceRouter);
router.use("/leaves", leavesRouter);
router.use("/payroll", payrollRouter);
router.use("/timesheets", timesheetsRouter);
router.use("/performance", performanceRouter);
router.use("/dashboard", dashboardRouter);
router.use("/branding", brandingRouter);
router.use("/biometrics", biometricsRouter);
router.use("/documents", documentsRouter);
router.use("/holidays", holidaysRouter);
router.use("/announcements", announcementsRouter);
router.use("/policies", policiesRouter);
router.use("/leave-rules", leaveRulesRouter);
router.use("/admin", adminRouter);
router.use("/upload", uploadRouter);
router.use("/audit-logs", auditLogsRouter);
router.use("/roles", rolesRouter);
router.use("/export", exportImportRouter);

export default router;
