import { Router, type IRouter } from "express";
import healthRouter from "./health.js";
import authRouter from "./auth.js";
import employeesRouter from "./employees.js";
import departmentsRouter from "./departments.js";
import attendanceRouter from "./attendance.js";
import leavesRouter from "./leaves.js";
import payrollRouter from "./payroll.js";
import timesheetsRouter from "./timesheets.js";
import performanceRouter from "./performance.js";
import dashboardRouter from "./dashboard.js";
import brandingRouter from "./branding.js";
import attendanceSettingsRouter from "./attendance-settings.js";
import biometricsRouter from "./biometrics.js";
import documentsRouter from "./documents.js";
import holidaysRouter from "./holidays.js";
import announcementsRouter from "./announcements.js";
import policiesRouter from "./policies.js";

const router: IRouter = Router();

router.use(healthRouter);
router.use("/auth", authRouter);
router.use("/employees", employeesRouter);
router.use("/departments", departmentsRouter);
router.use("/attendance", attendanceRouter);
router.use("/leaves", leavesRouter);
router.use("/payroll", payrollRouter);
router.use("/timesheets", timesheetsRouter);
router.use("/performance", performanceRouter);
router.use("/dashboard", dashboardRouter);
router.use("/branding", brandingRouter);
router.use("/attendance-settings", attendanceSettingsRouter);
router.use("/biometrics", biometricsRouter);
router.use("/documents", documentsRouter);
router.use("/holidays", holidaysRouter);
router.use("/announcements", announcementsRouter);
router.use("/policies", policiesRouter);

export default router;
